server:
  port: 9000

spring:
  profiles: dev
  application:
    name: MusicRecommender
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost{ADD DB CONNECTION HERE}
    username: {DB USERNAME}
    password: {DB PASSWORD}