server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: MusicRecommender

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://clouddb.c554t2pimfma.af-south-1.rds.amazonaws.com;databaseName=Artists_DB;encrypt=true;trustServerCertificate=true;
    username: admin
    password: gjc3CD5eHq9Z8cs
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
      dialect: org.hibernate.dialect.SQLServer2019Dialect
      format-sql: true


mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

music-rec:
  redirect:
    url: redirect:swagger-ui.html

logging:
  level:
    org.springframework: INFO
    com.music: DEBUG