server:
  port: 9000

spring:
  config:
    activate:
      on-profile: dev
#  profiles: dev
  application:
    name: MusicRecommender
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://clouddb.c554t2pimfma.af-south-1.rds.amazonaws.com
    username: admin
    password: gjc3CD5eHq9Z8cs
#  jpa:
#    hibernate:
#      ddl-auto: validate
#      dialect: org.hibernate.dialect.SQLServer2019Dialect
#      format-sql: true
#    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

musicrec:
  redirect:
    url: redirect:swagger-ui.html

logging:
  level:
    org.springframework: INFO
    com.music: DEBUG