server:
  port: 9000

spring:
  config:
    activate:
      on-profile: dev
#  profiles: dev
  application:
    name: MusicRecommender


#spring:
#  datasource:
#  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

#spring:
#  datasource:
#  url:jdbc:sqlserver://enpointur:1433;databaseName=dbname;encrypt=true;trustServerCertificate=true;
#spring.datasource.username=username
#spring.datasource.password=password
#spring.jpa.show-sql=true
#spring.datasource.hikari.maximum-pool-size=2
#spring.jpa.open-in-view=false
#spring.jpa.hibernate.format_sql=true
#spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.EJB3NamingStrategy
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://clouddb.c554t2pimfma.af-south-1.rds.amazonaws.com;databaseName=Artists_DB;encrypt=true;trustServerCertificate=true;
    username: admin
    password: gjc3CD5eHq9Z8cs
  jpa:
#      ddl-auto: validate
#      dialect: org.hibernate.dialect.SQLServer2019Dialect
#      format-sql: true
    show-sql: true
    hibernate:
      format_sql: true
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

musicrec:
  redirect:
    url: redirect:swagger-ui.html

logging:
  level:
    org.springframework: INFO
    com.music: DEBUG